{{- if not .Values.coordinator.azureCredentials.secretName }}
{{- if and .Values.coordinator.azureCredentials.clientID .Values.coordinator.azureCredentials.tenantID .Values.coordinator.azureCredentials.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: coordinator-azure-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  AZURE_CLIENT_ID: {{ .Values.coordinator.azureCredentials.clientID | b64enc }}
  AZURE_TENANT_ID: {{ .Values.coordinator.azureCredentials.tenantID | b64enc }}
  AZURE_CLIENT_SECRET: {{ .Values.coordinator.azureCredentials.clientSecret | b64enc }}
{{- end }}
{{- end }}
