name: Publish docs to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - docs/**
      - .github/workflows/docs-publish.yml
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    paths:
      - docs/**
      - .github/workflows/docs-publish.yml

permissions:
  contents: write
  pull-requests: write

jobs:
  preview:
    name: Preview docs
    runs-on: ubuntu-24.04
    if: (github.repository_owner == github.event.pull_request.head.repo.owner.login) && (github.event_name == 'pull_request')
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set base URL
        run: |
          sed -i "s|baseUrl: '/marblerun/'|baseUrl: '/marblerun/pr-preview/pr-${{ github.event.number }}/'|" ./docs/docusaurus.config.js

      - name: Build
        working-directory: ./docs
        run: |
          npm i && npm run build

      - name: Deploy Preview
        uses: rossjrw/pr-preview-action@ffa7509e91a3ec8dfc2e5536c4d5c1acdf7a6de9 # v1.8.1
        with:
          source-dir: ./docs/build

  publish:
    name: Publish docs to GitHub Pages
    runs-on: ubuntu-24.04
    if: github.event_name == 'push' && github.ref_name == 'master'
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Build
        working-directory: ./docs
        run: |
          npm i && npm run build

      - name: Publish
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        with:
          folder: ./docs/build
          branch: gh-pages
          clean-exclude: pr-preview
          force: false
