name: Publish docs to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - docs/**
      - .github/workflows/docs-publish.yml
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    paths:
      - docs/**
      - .github/workflows/docs-publish.yml

permissions:
  contents: write
  pull-requests: write

jobs:
  preview:
    name: Preview docs
    runs-on: ubuntu-24.04
    if: (github.repository_owner == github.event.pull_request.head.repo.owner.login) && (github.event_name == 'pull_request')
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Set base URL
        run: |
          sed -i "s|baseUrl: '/marblerun/'|baseUrl: '/marblerun/pr-preview/pr-${{ github.event.number }}/'|" ./docs/docusaurus.config.js

      - name: Build
        working-directory: ./docs
        run: |
          npm i && npm run build

      - name: Deploy Preview
        uses: rossjrw/pr-preview-action@5fd5f8e2f88e735fc3d1151302b32242037e3962 # v1.8.0
        with:
          source-dir: ./docs/build

  publish:
    name: Publish docs to GitHub Pages
    runs-on: ubuntu-24.04
    if: github.event_name == 'push' && github.ref_name == 'master'
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Build
        working-directory: ./docs
        run: |
          npm i && npm run build

      - name: Publish
        uses: JamesIves/github-pages-deploy-action@9d877eea73427180ae43cf98e8914934fe157a1a # v4.7.6
        with:
          folder: ./docs/build
          branch: gh-pages
          clean-exclude: pr-preview
          force: false
