name: e2e weekly Test

on:
  schedule:
    - cron: '30 12 * * 6' # run every Saturday at 12:30 UTC

jobs:
  weekly-test:
    name: Weekly e2e Test
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    uses: ./.github/workflows/e2e.yaml
    with:
      vmType: 'Standard_DC4s_v3'
      nodes: 3
      replicas: 3
      parallel: 1

  notify-failure:
    runs-on: ubuntu-24.04
    name: Notify Failure
    needs: weekly-test
    continue-on-error: true
    if: failure()
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Notify Failure
        uses: ./.github/actions/notify_failure
        with:
          teamsWebhookUri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
